config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  root :to => "contents#index"
    
    
  resource :homes do
   get :about, on: :collection
  end


  resources :users, only: [:index, :show, :edit, :update] do
   resource :relationships, only: [:index, :create, :destroy]
  end
  

  resources :contents do
   resource :favorites, only: [:index, :create, :destroy]
   resources :comments, only: [:index, :create, :destroy]
  end
  
  
  get 'chat/:id' => 'chats#show', as: 'chat'

  resources :chats, only: [:index, :create]
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/content.rb
class Content < ApplicationRecord
  belong_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :content
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats
  has_many :user_rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #attachment :profile_image


  has_many :contents
  has_many :comments
  has_many :favotites
  has_many :chats
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  
  
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  
  has_many :followings, through: :active_relationships, source: :follower
  
  
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  
  has_many :followers, through: :passive_relationships, source: :following

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Re:room</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <header class="sticky-top">
      <nav class="navbar navbar-expand-lg navbar-light mb-4">
        <%= link_to "Re:room", root_path %>
       
     
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto mr-3">
            <% if user_signed_in? %>
              <li class="nav-item mx-2"><%= link_to "My page", user_path(current_user), class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Chats", chats_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Users", users_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Contents", root_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "About", about_homes_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
            <% else %>
              <li class="nav-item mx-2"><%= link_to "About", about_homes_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item mx-2"><%= link_to "Log in", new_user_session_path, class: "nav-link" %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    
    <main>
    <%= yield %>
    </main>
    
  </body>
</html>